// Compile the question packs in ./questions/*.json into src/bank.ts.
//
// A pack is one topic:
//   { "topic": "Science & Nature", "icon": "🔬",
//     "questions": [ { "q": "…?", "a": ["CORRECT", "wrong", "wrong", "wrong"], "d": 2 } ] }
// The FIRST answer is always the correct one (the module shuffles at play
// time); "d" is the difficulty 1 easy · 2 medium · 3 hard and sets the odds.
//
// Runs automatically before every build/publish (see package.json and
// publish.sh). The output is committed too, so `spacetime publish` works
// straight from a checkout. Questions written IN the game live in the
// database instead (see the `question` table in src/index.ts); this file is
// only the built-in bank, synced into that same table on first use.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const dir = join(here, 'questions');
const files = readdirSync(dir).filter(f => f.endsWith('.json')).sort();

const fail = (file, msg) => {
  console.error(`questions/${file}: ${msg}`);
  process.exit(1);
};

const seen = new Set();
const packs = [];
for (const file of files) {
  let pack;
  try {
    pack = JSON.parse(readFileSync(join(dir, file), 'utf8'));
  } catch (err) {
    fail(file, `not valid JSON (${err.message})`);
  }
  if (typeof pack.topic !== 'string' || !pack.topic.trim()) fail(file, '"topic" must be a non-empty string');
  if (!Array.isArray(pack.questions) || pack.questions.length === 0) fail(file, '"questions" must be a non-empty array');
  const topic = pack.topic.trim();
  if (seen.has(topic.toLowerCase())) fail(file, `topic "${topic}" appears in two packs`);
  seen.add(topic.toLowerCase());
  const questions = pack.questions.map((q, i) => {
    const where = `question #${i + 1}`;
    if (typeof q.q !== 'string' || q.q.trim().length < 5) fail(file, `${where}: "q" must be a question of at least 5 characters`);
    if (!Array.isArray(q.a) || q.a.length !== 4) fail(file, `${where}: "a" must be exactly 4 answers (correct one first)`);
    const answers = q.a.map(a => String(a).trim());
    if (answers.some(a => !a || a.length > 60)) fail(file, `${where}: every answer must be 1–60 characters`);
    if (new Set(answers.map(a => a.toLowerCase())).size !== 4) fail(file, `${where}: answers must be distinct`);
    const d = q.d ?? 2;
    if (![1, 2, 3].includes(d)) fail(file, `${where}: "d" (difficulty) must be 1, 2 or 3`);
    return { q: q.q.trim(), a: answers, d };
  });
  packs.push({ topic, icon: String(pack.icon ?? '❔').trim().slice(0, 4) || '❔', questions });
}

const version = createHash('sha1').update(JSON.stringify(packs)).digest('hex').slice(0, 12);
const out = `// GENERATED by gen-bank.mjs from questions/*.json — do not edit by hand.
// ${packs.length} topics, ${packs.reduce((n, p) => n + p.questions.length, 0)} questions.
export type BankQuestion = { q: string; a: string[]; d: number };
export type BankTopic = { topic: string; icon: string; questions: BankQuestion[] };
export const BANK_VERSION = ${JSON.stringify(version)};
export const BANK: BankTopic[] = ${JSON.stringify(packs, null, 2)};
`;
writeFileSync(join(here, 'src', 'bank.ts'), out);
console.log(`bank.ts: ${packs.length} topics, ${packs.reduce((n, p) => n + p.questions.length, 0)} questions (version ${version})`);
