// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ActReducer from "../act_reducer";
import AddQuestionReducer from "../add_question_reducer";
import AddTopicReducer from "../add_topic_reducer";
import AnswerReducer from "../answer_reducer";
import CallOutReducer from "../call_out_reducer";
import CreateChampionshipRoomReducer from "../create_championship_room_reducer";
import CreatePubReducer from "../create_pub_reducer";
import DeleteQuestionReducer from "../delete_question_reducer";
import JoinPubReducer from "../join_pub_reducer";
import KickPlayerReducer from "../kick_player_reducer";
import LeavePubReducer from "../leave_pub_reducer";
import RestoreAccountReducer from "../restore_account_reducer";
import SendChatReducer from "../send_chat_reducer";
import SendEmoteReducer from "../send_emote_reducer";
import SetAttentionReducer from "../set_attention_reducer";
import SetAvatarReducer from "../set_avatar_reducer";
import SetInputReducer from "../set_input_reducer";
import SetNameReducer from "../set_name_reducer";
import SetPubSettingsReducer from "../set_pub_settings_reducer";
import SetPubTopicsReducer from "../set_pub_topics_reducer";
import SetReadyReducer from "../set_ready_reducer";
import SetTeamReducer from "../set_team_reducer";
import StartQuizReducer from "../start_quiz_reducer";

export type ActParams = __Infer<typeof ActReducer>;
export type AddQuestionParams = __Infer<typeof AddQuestionReducer>;
export type AddTopicParams = __Infer<typeof AddTopicReducer>;
export type AnswerParams = __Infer<typeof AnswerReducer>;
export type CallOutParams = __Infer<typeof CallOutReducer>;
export type CreateChampionshipRoomParams = __Infer<typeof CreateChampionshipRoomReducer>;
export type CreatePubParams = __Infer<typeof CreatePubReducer>;
export type DeleteQuestionParams = __Infer<typeof DeleteQuestionReducer>;
export type JoinPubParams = __Infer<typeof JoinPubReducer>;
export type KickPlayerParams = __Infer<typeof KickPlayerReducer>;
export type LeavePubParams = __Infer<typeof LeavePubReducer>;
export type RestoreAccountParams = __Infer<typeof RestoreAccountReducer>;
export type SendChatParams = __Infer<typeof SendChatReducer>;
export type SendEmoteParams = __Infer<typeof SendEmoteReducer>;
export type SetAttentionParams = __Infer<typeof SetAttentionReducer>;
export type SetAvatarParams = __Infer<typeof SetAvatarReducer>;
export type SetInputParams = __Infer<typeof SetInputReducer>;
export type SetNameParams = __Infer<typeof SetNameReducer>;
export type SetPubSettingsParams = __Infer<typeof SetPubSettingsReducer>;
export type SetPubTopicsParams = __Infer<typeof SetPubTopicsReducer>;
export type SetReadyParams = __Infer<typeof SetReadyReducer>;
export type SetTeamParams = __Infer<typeof SetTeamReducer>;
export type StartQuizParams = __Infer<typeof StartQuizReducer>;

