// GENERATED by gen-bank.mjs from questions/*.json — do not edit by hand.
// 9 topics, 124 questions.
export type BankQuestion = { q: string; a: string[]; d: number };
export type BankTopic = { topic: string; icon: string; questions: BankQuestion[] };
export const BANK_VERSION = "1cff48fa7315";
export const BANK: BankTopic[] = [
  {
    "topic": "General Knowledge",
    "icon": "🧠",
    "questions": [
      {
        "q": "How many sides does a hexagon have?",
        "a": [
          "Six",
          "Five",
          "Seven",
          "Eight"
        ],
        "d": 1
      },
      {
        "q": "What is the largest planet in our solar system?",
        "a": [
          "Jupiter",
          "Saturn",
          "Neptune",
          "Earth"
        ],
        "d": 1
      },
      {
        "q": "How many minutes are there in a full day?",
        "a": [
          "1,440",
          "1,240",
          "1,640",
          "2,400"
        ],
        "d": 1
      },
      {
        "q": "What is the currency of Japan?",
        "a": [
          "Yen",
          "Won",
          "Yuan",
          "Ringgit"
        ],
        "d": 2
      },
      {
        "q": "Which language has the most native speakers in the world?",
        "a": [
          "Mandarin Chinese",
          "English",
          "Spanish",
          "Hindi"
        ],
        "d": 2
      },
      {
        "q": "What does the Roman numeral XL represent?",
        "a": [
          "40",
          "60",
          "90",
          "400"
        ],
        "d": 2
      },
      {
        "q": "How many keys does a standard piano have?",
        "a": [
          "88",
          "76",
          "96",
          "100"
        ],
        "d": 2
      },
      {
        "q": "What is the collective noun for a group of owls?",
        "a": [
          "A parliament",
          "A murder",
          "A congress",
          "A school"
        ],
        "d": 3
      },
      {
        "q": "Which word is spelled the same forwards and backwards?",
        "a": [
          "Level",
          "Lever",
          "Layer",
          "Lower"
        ],
        "d": 3
      },
      {
        "q": "How many time zones does Russia span?",
        "a": [
          "11",
          "7",
          "9",
          "13"
        ],
        "d": 3
      },
      {
        "q": "What colour do you get by mixing blue and yellow?",
        "a": [
          "Green",
          "Purple",
          "Orange",
          "Brown"
        ],
        "d": 1
      },
      {
        "q": "Which is the only letter not appearing in any US state name?",
        "a": [
          "Q",
          "Z",
          "X",
          "J"
        ],
        "d": 2
      },
      {
        "q": "What is the fear of long words called?",
        "a": [
          "Hippopotomonstrosesquippedaliophobia",
          "Logophobia",
          "Verbophobia",
          "Sesquiphobia"
        ],
        "d": 3
      }
    ]
  },
  {
    "topic": "Science & Nature",
    "icon": "🔬",
    "questions": [
      {
        "q": "What is the chemical symbol for water?",
        "a": [
          "H2O",
          "CO2",
          "O2",
          "HO"
        ],
        "d": 1
      },
      {
        "q": "How many legs does a spider have?",
        "a": [
          "Eight",
          "Six",
          "Ten",
          "Twelve"
        ],
        "d": 1
      },
      {
        "q": "What gas do plants absorb from the air?",
        "a": [
          "Carbon dioxide",
          "Oxygen",
          "Nitrogen",
          "Hydrogen"
        ],
        "d": 1
      },
      {
        "q": "What is the hardest natural substance on Earth?",
        "a": [
          "Diamond",
          "Titanium",
          "Quartz",
          "Graphite"
        ],
        "d": 2
      },
      {
        "q": "What is the largest organ of the human body?",
        "a": [
          "Skin",
          "Liver",
          "Brain",
          "Lungs"
        ],
        "d": 2
      },
      {
        "q": "At what temperature are Celsius and Fahrenheit equal?",
        "a": [
          "-40°",
          "0°",
          "32°",
          "-20°"
        ],
        "d": 2
      },
      {
        "q": "Which planet is known as the Red Planet?",
        "a": [
          "Mars",
          "Venus",
          "Mercury",
          "Jupiter"
        ],
        "d": 2
      },
      {
        "q": "What is the most abundant gas in Earth’s atmosphere?",
        "a": [
          "Nitrogen",
          "Oxygen",
          "Argon",
          "Carbon dioxide"
        ],
        "d": 3
      },
      {
        "q": "What is the chemical symbol for gold?",
        "a": [
          "Au",
          "Ag",
          "Gd",
          "Go"
        ],
        "d": 3
      },
      {
        "q": "How many bones are in the adult human body?",
        "a": [
          "206",
          "186",
          "226",
          "256"
        ],
        "d": 3
      },
      {
        "q": "What is the speed of light, roughly, in km per second?",
        "a": [
          "300,000",
          "30,000",
          "3,000,000",
          "150,000"
        ],
        "d": 3
      },
      {
        "q": "Which animal is the largest living mammal?",
        "a": [
          "Blue whale",
          "African elephant",
          "Giraffe",
          "Orca"
        ],
        "d": 1
      },
      {
        "q": "What part of the plant conducts photosynthesis?",
        "a": [
          "Leaves",
          "Roots",
          "Stem",
          "Flowers"
        ],
        "d": 2
      },
      {
        "q": "What is the powerhouse of the cell?",
        "a": [
          "Mitochondria",
          "Nucleus",
          "Ribosome",
          "Golgi body"
        ],
        "d": 3
      }
    ]
  },
  {
    "topic": "Geography",
    "icon": "🌍",
    "questions": [
      {
        "q": "What is the capital of France?",
        "a": [
          "Paris",
          "Lyon",
          "Marseille",
          "Nice"
        ],
        "d": 1
      },
      {
        "q": "Which is the largest ocean on Earth?",
        "a": [
          "Pacific",
          "Atlantic",
          "Indian",
          "Arctic"
        ],
        "d": 1
      },
      {
        "q": "On which continent is Brazil?",
        "a": [
          "South America",
          "Africa",
          "North America",
          "Europe"
        ],
        "d": 1
      },
      {
        "q": "What is the capital of Australia?",
        "a": [
          "Canberra",
          "Sydney",
          "Melbourne",
          "Perth"
        ],
        "d": 2
      },
      {
        "q": "Which is the longest river in the world?",
        "a": [
          "Nile",
          "Amazon",
          "Yangtze",
          "Mississippi"
        ],
        "d": 2
      },
      {
        "q": "Mount Everest sits on the border of Nepal and which country?",
        "a": [
          "China",
          "India",
          "Bhutan",
          "Pakistan"
        ],
        "d": 2
      },
      {
        "q": "Which country has the most islands?",
        "a": [
          "Sweden",
          "Indonesia",
          "Philippines",
          "Canada"
        ],
        "d": 2
      },
      {
        "q": "What is the smallest country in the world by area?",
        "a": [
          "Vatican City",
          "Monaco",
          "San Marino",
          "Liechtenstein"
        ],
        "d": 3
      },
      {
        "q": "What is the capital of Canada?",
        "a": [
          "Ottawa",
          "Toronto",
          "Vancouver",
          "Montreal"
        ],
        "d": 3
      },
      {
        "q": "Which desert is the largest hot desert in the world?",
        "a": [
          "Sahara",
          "Gobi",
          "Kalahari",
          "Arabian"
        ],
        "d": 3
      },
      {
        "q": "Which two countries share the longest international border?",
        "a": [
          "Canada and the USA",
          "Russia and China",
          "Argentina and Chile",
          "Russia and Kazakhstan"
        ],
        "d": 3
      },
      {
        "q": "Which country is shaped like a boot?",
        "a": [
          "Italy",
          "Spain",
          "Portugal",
          "Greece"
        ],
        "d": 1
      },
      {
        "q": "What is the capital of Norway?",
        "a": [
          "Oslo",
          "Bergen",
          "Stockholm",
          "Helsinki"
        ],
        "d": 2
      },
      {
        "q": "Lake Baikal, the deepest lake on Earth, is in which country?",
        "a": [
          "Russia",
          "Mongolia",
          "Kazakhstan",
          "China"
        ],
        "d": 3
      }
    ]
  },
  {
    "topic": "History",
    "icon": "🏛️",
    "questions": [
      {
        "q": "In which year did the Second World War end?",
        "a": [
          "1945",
          "1944",
          "1946",
          "1939"
        ],
        "d": 1
      },
      {
        "q": "Who was the first person to walk on the Moon?",
        "a": [
          "Neil Armstrong",
          "Buzz Aldrin",
          "Yuri Gagarin",
          "John Glenn"
        ],
        "d": 1
      },
      {
        "q": "The Titanic sank in which year?",
        "a": [
          "1912",
          "1905",
          "1921",
          "1898"
        ],
        "d": 2
      },
      {
        "q": "Who was the first President of the United States?",
        "a": [
          "George Washington",
          "Thomas Jefferson",
          "Abraham Lincoln",
          "John Adams"
        ],
        "d": 2
      },
      {
        "q": "In which city was the Berlin Wall?",
        "a": [
          "Berlin",
          "Munich",
          "Hamburg",
          "Frankfurt"
        ],
        "d": 2
      },
      {
        "q": "Which ancient wonder was located in Alexandria?",
        "a": [
          "The Lighthouse",
          "The Hanging Gardens",
          "The Colossus",
          "The Mausoleum"
        ],
        "d": 2
      },
      {
        "q": "In which year did the Berlin Wall fall?",
        "a": [
          "1989",
          "1991",
          "1987",
          "1985"
        ],
        "d": 3
      },
      {
        "q": "Who was the British Prime Minister for most of the Second World War?",
        "a": [
          "Winston Churchill",
          "Neville Chamberlain",
          "Clement Attlee",
          "Anthony Eden"
        ],
        "d": 3
      },
      {
        "q": "The Magna Carta was sealed in which year?",
        "a": [
          "1215",
          "1066",
          "1315",
          "1415"
        ],
        "d": 3
      },
      {
        "q": "Which empire was ruled by Genghis Khan?",
        "a": [
          "Mongol",
          "Ottoman",
          "Persian",
          "Roman"
        ],
        "d": 3
      },
      {
        "q": "Which ancient civilisation built the pyramids of Giza?",
        "a": [
          "Egyptians",
          "Romans",
          "Greeks",
          "Aztecs"
        ],
        "d": 1
      },
      {
        "q": "Which ship carried the Pilgrims to America in 1620?",
        "a": [
          "Mayflower",
          "Santa Maria",
          "Endeavour",
          "Beagle"
        ],
        "d": 2
      },
      {
        "q": "Who painted the ceiling of the Sistine Chapel?",
        "a": [
          "Michelangelo",
          "Leonardo da Vinci",
          "Raphael",
          "Donatello"
        ],
        "d": 3
      }
    ]
  },
  {
    "topic": "Sport",
    "icon": "⚽",
    "questions": [
      {
        "q": "How many players are on a football (soccer) team on the pitch?",
        "a": [
          "11",
          "10",
          "12",
          "9"
        ],
        "d": 1
      },
      {
        "q": "In which sport would you perform a slam dunk?",
        "a": [
          "Basketball",
          "Volleyball",
          "Tennis",
          "Rugby"
        ],
        "d": 1
      },
      {
        "q": "How many rings are on the Olympic flag?",
        "a": [
          "Five",
          "Four",
          "Six",
          "Seven"
        ],
        "d": 1
      },
      {
        "q": "How many points is a touchdown worth in American football?",
        "a": [
          "6",
          "7",
          "3",
          "5"
        ],
        "d": 2
      },
      {
        "q": "In tennis, what score comes after deuce when a player wins a point?",
        "a": [
          "Advantage",
          "Game",
          "Love",
          "Forty"
        ],
        "d": 2
      },
      {
        "q": "How long is a marathon, to the nearest kilometre?",
        "a": [
          "42 km",
          "40 km",
          "45 km",
          "38 km"
        ],
        "d": 2
      },
      {
        "q": "Which country hosted the 2016 Summer Olympics?",
        "a": [
          "Brazil",
          "China",
          "United Kingdom",
          "Japan"
        ],
        "d": 2
      },
      {
        "q": "How many holes are played in a standard round of golf?",
        "a": [
          "18",
          "9",
          "20",
          "16"
        ],
        "d": 3
      },
      {
        "q": "What is the maximum break in snooker?",
        "a": [
          "147",
          "155",
          "140",
          "180"
        ],
        "d": 3
      },
      {
        "q": "Which country has won the most FIFA World Cups?",
        "a": [
          "Brazil",
          "Germany",
          "Italy",
          "Argentina"
        ],
        "d": 3
      },
      {
        "q": "In darts, what is the highest score with three darts?",
        "a": [
          "180",
          "150",
          "171",
          "200"
        ],
        "d": 3
      },
      {
        "q": "What colour jersey does the Tour de France leader wear?",
        "a": [
          "Yellow",
          "Green",
          "White",
          "Polka dot"
        ],
        "d": 1
      },
      {
        "q": "How many players are on an ice hockey team on the ice?",
        "a": [
          "6",
          "5",
          "7",
          "8"
        ],
        "d": 2
      },
      {
        "q": "What is a score of one under par called in golf?",
        "a": [
          "Birdie",
          "Eagle",
          "Bogey",
          "Albatross"
        ],
        "d": 3
      }
    ]
  },
  {
    "topic": "Film & TV",
    "icon": "🎬",
    "questions": [
      {
        "q": "Who directed \"Jurassic Park\" (1993)?",
        "a": [
          "Steven Spielberg",
          "James Cameron",
          "George Lucas",
          "Ridley Scott"
        ],
        "d": 1
      },
      {
        "q": "What kind of animal is Simba in \"The Lion King\"?",
        "a": [
          "Lion",
          "Tiger",
          "Leopard",
          "Cheetah"
        ],
        "d": 1
      },
      {
        "q": "Which wizarding school does Harry Potter attend?",
        "a": [
          "Hogwarts",
          "Durmstrang",
          "Beauxbatons",
          "Ilvermorny"
        ],
        "d": 1
      },
      {
        "q": "In \"The Matrix\", which pill does Neo take?",
        "a": [
          "Red",
          "Blue",
          "Green",
          "White"
        ],
        "d": 2
      },
      {
        "q": "Who played Jack in \"Titanic\" (1997)?",
        "a": [
          "Leonardo DiCaprio",
          "Brad Pitt",
          "Matt Damon",
          "Johnny Depp"
        ],
        "d": 2
      },
      {
        "q": "What is the name of the coffee shop in \"Friends\"?",
        "a": [
          "Central Perk",
          "The Grind",
          "Cafe Nervosa",
          "Monk’s"
        ],
        "d": 2
      },
      {
        "q": "Which film features the line \"I’ll be back\"?",
        "a": [
          "The Terminator",
          "RoboCop",
          "Predator",
          "Die Hard"
        ],
        "d": 2
      },
      {
        "q": "Which film won the first ever Academy Award for Best Picture?",
        "a": [
          "Wings",
          "Sunrise",
          "The Jazz Singer",
          "Metropolis"
        ],
        "d": 3
      },
      {
        "q": "In \"Breaking Bad\", what is Walter White’s alias?",
        "a": [
          "Heisenberg",
          "Schrödinger",
          "Feynman",
          "Oppenheimer"
        ],
        "d": 3
      },
      {
        "q": "Who composed the score for \"Star Wars\"?",
        "a": [
          "John Williams",
          "Hans Zimmer",
          "Howard Shore",
          "James Horner"
        ],
        "d": 3
      },
      {
        "q": "What is the name of the fictional town in \"Stranger Things\"?",
        "a": [
          "Hawkins",
          "Derry",
          "Twin Peaks",
          "Riverdale"
        ],
        "d": 3
      },
      {
        "q": "Which superhero is known as the Caped Crusader?",
        "a": [
          "Batman",
          "Superman",
          "Spider-Man",
          "Iron Man"
        ],
        "d": 1
      },
      {
        "q": "In \"Finding Nemo\", what type of fish is Nemo?",
        "a": [
          "Clownfish",
          "Blue tang",
          "Angelfish",
          "Goldfish"
        ],
        "d": 2
      },
      {
        "q": "Which actor played the Joker in \"The Dark Knight\" (2008)?",
        "a": [
          "Heath Ledger",
          "Jack Nicholson",
          "Joaquin Phoenix",
          "Jared Leto"
        ],
        "d": 3
      }
    ]
  },
  {
    "topic": "Music",
    "icon": "🎵",
    "questions": [
      {
        "q": "How many strings does a standard guitar have?",
        "a": [
          "Six",
          "Four",
          "Five",
          "Seven"
        ],
        "d": 1
      },
      {
        "q": "Which band sang \"Hey Jude\"?",
        "a": [
          "The Beatles",
          "The Rolling Stones",
          "The Who",
          "Queen"
        ],
        "d": 1
      },
      {
        "q": "Which artist is known as the \"King of Pop\"?",
        "a": [
          "Michael Jackson",
          "Elvis Presley",
          "Prince",
          "Freddie Mercury"
        ],
        "d": 1
      },
      {
        "q": "Which band released the album \"The Dark Side of the Moon\"?",
        "a": [
          "Pink Floyd",
          "Led Zeppelin",
          "Genesis",
          "Yes"
        ],
        "d": 2
      },
      {
        "q": "What instrument does a pianist play?",
        "a": [
          "Piano",
          "Violin",
          "Harp",
          "Cello"
        ],
        "d": 2
      },
      {
        "q": "Who sang \"Rolling in the Deep\"?",
        "a": [
          "Adele",
          "Beyoncé",
          "Rihanna",
          "Lady Gaga"
        ],
        "d": 2
      },
      {
        "q": "Which Swedish group sang \"Dancing Queen\"?",
        "a": [
          "ABBA",
          "Roxette",
          "Ace of Base",
          "Europe"
        ],
        "d": 2
      },
      {
        "q": "How many symphonies did Beethoven complete?",
        "a": [
          "Nine",
          "Seven",
          "Twelve",
          "Five"
        ],
        "d": 3
      },
      {
        "q": "Which Queen song features the line \"Is this the real life?\"",
        "a": [
          "Bohemian Rhapsody",
          "We Are the Champions",
          "Don’t Stop Me Now",
          "Somebody to Love"
        ],
        "d": 3
      },
      {
        "q": "What was Elvis Presley’s middle name?",
        "a": [
          "Aaron",
          "Alan",
          "Andrew",
          "Arthur"
        ],
        "d": 3
      },
      {
        "q": "Which composer wrote \"The Four Seasons\"?",
        "a": [
          "Vivaldi",
          "Bach",
          "Mozart",
          "Handel"
        ],
        "d": 3
      },
      {
        "q": "Which instrument has 88 keys?",
        "a": [
          "Piano",
          "Organ",
          "Accordion",
          "Harpsichord"
        ],
        "d": 1
      },
      {
        "q": "Which rapper released \"The Marshall Mathers LP\"?",
        "a": [
          "Eminem",
          "Dr. Dre",
          "Jay-Z",
          "50 Cent"
        ],
        "d": 2
      },
      {
        "q": "In which city did The Beatles form?",
        "a": [
          "Liverpool",
          "Manchester",
          "London",
          "Birmingham"
        ],
        "d": 3
      }
    ]
  },
  {
    "topic": "Food & Drink",
    "icon": "🍺",
    "questions": [
      {
        "q": "Which fruit is traditionally used to make guacamole?",
        "a": [
          "Avocado",
          "Tomato",
          "Lime",
          "Mango"
        ],
        "d": 1
      },
      {
        "q": "What is sushi traditionally wrapped in?",
        "a": [
          "Seaweed",
          "Rice paper",
          "Lettuce",
          "Tofu skin"
        ],
        "d": 1
      },
      {
        "q": "Which country is famous for inventing pizza?",
        "a": [
          "Italy",
          "Greece",
          "France",
          "Spain"
        ],
        "d": 1
      },
      {
        "q": "What is the main ingredient in hummus?",
        "a": [
          "Chickpeas",
          "Lentils",
          "Beans",
          "Peas"
        ],
        "d": 2
      },
      {
        "q": "Which spirit is the base of a mojito?",
        "a": [
          "Rum",
          "Vodka",
          "Gin",
          "Tequila"
        ],
        "d": 2
      },
      {
        "q": "What type of pastry is used for profiteroles?",
        "a": [
          "Choux",
          "Puff",
          "Shortcrust",
          "Filo"
        ],
        "d": 2
      },
      {
        "q": "Which nut is used to make marzipan?",
        "a": [
          "Almond",
          "Peanut",
          "Hazelnut",
          "Cashew"
        ],
        "d": 2
      },
      {
        "q": "What is the most expensive spice in the world by weight?",
        "a": [
          "Saffron",
          "Vanilla",
          "Cardamom",
          "Truffle salt"
        ],
        "d": 3
      },
      {
        "q": "Which cheese is traditionally used in a tiramisu?",
        "a": [
          "Mascarpone",
          "Ricotta",
          "Mozzarella",
          "Cream cheese"
        ],
        "d": 3
      },
      {
        "q": "From which country does the drink sake originate?",
        "a": [
          "Japan",
          "China",
          "Korea",
          "Thailand"
        ],
        "d": 3
      },
      {
        "q": "What is the Scoville scale used to measure?",
        "a": [
          "Chilli heat",
          "Sweetness",
          "Alcohol content",
          "Acidity"
        ],
        "d": 3
      },
      {
        "q": "Which drink is made from fermented apples?",
        "a": [
          "Cider",
          "Mead",
          "Ale",
          "Perry"
        ],
        "d": 1
      },
      {
        "q": "Which grain is used to make traditional Scotch whisky?",
        "a": [
          "Barley",
          "Corn",
          "Rye",
          "Wheat"
        ],
        "d": 2
      },
      {
        "q": "What does IPA stand for in beer?",
        "a": [
          "India Pale Ale",
          "Imperial Pale Ale",
          "Irish Pale Ale",
          "International Pale Ale"
        ],
        "d": 3
      }
    ]
  },
  {
    "topic": "Tech & Games",
    "icon": "🎮",
    "questions": [
      {
        "q": "What does \"www\" stand for in a web address?",
        "a": [
          "World Wide Web",
          "Wide World Web",
          "World Web Wide",
          "Web World Wide"
        ],
        "d": 1
      },
      {
        "q": "Which company makes the PlayStation?",
        "a": [
          "Sony",
          "Nintendo",
          "Microsoft",
          "Sega"
        ],
        "d": 1
      },
      {
        "q": "What is the name of Mario’s brother?",
        "a": [
          "Luigi",
          "Wario",
          "Toad",
          "Yoshi"
        ],
        "d": 1
      },
      {
        "q": "What does CPU stand for?",
        "a": [
          "Central Processing Unit",
          "Computer Processing Unit",
          "Central Program Unit",
          "Core Processing Unit"
        ],
        "d": 2
      },
      {
        "q": "In which game do you build with blocks in a procedurally generated world?",
        "a": [
          "Minecraft",
          "Terraria",
          "Roblox",
          "Fortnite"
        ],
        "d": 2
      },
      {
        "q": "Which company created the iPhone?",
        "a": [
          "Apple",
          "Samsung",
          "Google",
          "Nokia"
        ],
        "d": 2
      },
      {
        "q": "How many bits are in a byte?",
        "a": [
          "8",
          "4",
          "16",
          "10"
        ],
        "d": 2
      },
      {
        "q": "What was the first video game console released by Nintendo in North America?",
        "a": [
          "Nintendo Entertainment System",
          "Game Boy",
          "Super Nintendo",
          "Nintendo 64"
        ],
        "d": 3
      },
      {
        "q": "Which programming language is named after a snake?",
        "a": [
          "Python",
          "Cobra",
          "Viper",
          "Mamba"
        ],
        "d": 3
      },
      {
        "q": "In \"Pac-Man\", what colour is the ghost named Blinky?",
        "a": [
          "Red",
          "Pink",
          "Blue",
          "Orange"
        ],
        "d": 3
      },
      {
        "q": "What year was the first iPhone released?",
        "a": [
          "2007",
          "2005",
          "2009",
          "2010"
        ],
        "d": 3
      },
      {
        "q": "Which animal is the Linux mascot?",
        "a": [
          "Penguin",
          "Fox",
          "Cat",
          "Elephant"
        ],
        "d": 1
      },
      {
        "q": "What does HTML stand for?",
        "a": [
          "HyperText Markup Language",
          "HighText Machine Language",
          "HyperText Machine Language",
          "Home Tool Markup Language"
        ],
        "d": 2
      },
      {
        "q": "Which game popularised the battle royale genre on consoles in 2017?",
        "a": [
          "PlayerUnknown’s Battlegrounds",
          "Apex Legends",
          "Call of Duty: Warzone",
          "H1Z1"
        ],
        "d": 3
      }
    ]
  }
];
