// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  uid: __t.string(),
  provider: __t.u8(),
  displayName: __t.string().name("display_name"),
  avatarId: __t.u8().name("avatar_id"),
  xp: __t.u32(),
  level: __t.u16(),
  quizzes: __t.u16(),
  quizWins: __t.u16().name("quiz_wins"),
  questions: __t.u32(),
  correct: __t.u32(),
  bestCredits: __t.i32().name("best_credits"),
  phoneChecks: __t.u32().name("phone_checks"),
  createdAt: __t.timestamp().name("created_at"),
  lastSeen: __t.timestamp().name("last_seen"),
  rev: __t.u32(),
});
