// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  lobbyId: __t.u64().name("lobby_id"),
  senderId: __t.identity().name("sender_id"),
  senderName: __t.string().name("sender_name"),
  kind: __t.u8(),
  text: __t.string(),
  sentAt: __t.timestamp().name("sent_at"),
});
