// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  lobbyId: __t.u64().name("lobby_id"),
  questionIdx: __t.u8().name("question_idx"),
  identity: __t.identity(),
  name: __t.string(),
  stake: __t.u16(),
  answer: __t.u8(),
  correct: __t.bool(),
  delta: __t.i32(),
  answerMillis: __t.u32().name("answer_millis"),
  onPhone: __t.bool().name("on_phone"),
});
