// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  code: __t.string(),
  hostId: __t.identity().name("host_id"),
  status: __t.u8(),
  isPublic: __t.bool().name("is_public"),
  theme: __t.u8(),
  questionCount: __t.u8().name("question_count"),
  betSecs: __t.u8().name("bet_secs"),
  answerSecs: __t.u8().name("answer_secs"),
  teamMode: __t.bool().name("team_mode"),
  createdAt: __t.timestamp().name("created_at"),
  phase: __t.u8(),
  questionIdx: __t.u8().name("question_idx"),
  phaseEndsAt: __t.timestamp().name("phase_ends_at"),
  phaseStartedAt: __t.timestamp().name("phase_started_at"),
  timerGen: __t.u32().name("timer_gen"),
  drawn: __t.array(__t.u64()),
  topics: __t.array(__t.u64()),
  qTopic: __t.string().name("q_topic"),
  qIcon: __t.string().name("q_icon"),
  qDifficulty: __t.u8().name("q_difficulty"),
  qPayoutPct: __t.u16().name("q_payout_pct"),
  qText: __t.string().name("q_text"),
  qOptions: __t.array(__t.string()).name("q_options"),
  qCorrect: __t.u8().name("q_correct"),
  fastestName: __t.string().name("fastest_name"),
  mcText: __t.string().name("mc_text"),
  championName: __t.string().name("champion_name"),
  championshipLeg: __t.u64().name("championship_leg"),
});
