// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  topicId: __t.u64().name("topic_id"),
  difficulty: __t.u8(),
  text: __t.string(),
  correct: __t.string(),
  wrong: __t.array(__t.string()),
  authorId: __t.identity().name("author_id"),
  authorName: __t.string().name("author_name"),
  builtin: __t.bool(),
  bankKey: __t.string().name("bank_key"),
  createdAt: __t.timestamp().name("created_at"),
});
