// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  identity: __t.identity(),
  lobbyId: __t.u64().name("lobby_id"),
  pub: __t.string(),
  placing: __t.u8(),
  seats: __t.u8(),
  credits: __t.i32(),
  correct: __t.u16(),
  questions: __t.u16(),
  xpGained: __t.u32().name("xp_gained"),
  levelAfter: __t.u16().name("level_after"),
  won: __t.bool(),
  playedAt: __t.timestamp().name("played_at"),
});
