// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  name: __t.string(),
  avatarId: __t.u8().name("avatar_id"),
  lobbyId: __t.u64().name("lobby_id"),
  seat: __t.u8(),
  team: __t.u8(),
  online: __t.bool(),
  ready: __t.bool(),
  kicked: __t.bool(),
  x: __t.f32(),
  y: __t.f32(),
  dirX: __t.i8().name("dir_x"),
  dirY: __t.i8().name("dir_y"),
  actTicks: __t.u8().name("act_ticks"),
  actKind: __t.u8().name("act_kind"),
  credits: __t.i32(),
  stake: __t.u16(),
  answer: __t.u8(),
  answeredAt: __t.u64().name("answered_at"),
  lastDelta: __t.i32().name("last_delta"),
  lastCorrect: __t.bool().name("last_correct"),
  correct: __t.u16(),
  answered: __t.u16(),
  streak: __t.u8(),
  tabs: __t.u16(),
  attention: __t.u8(),
  attentionSince: __t.u64().name("attention_since"),
  phoneChecks: __t.u16().name("phone_checks"),
  phoneMicros: __t.u64().name("phone_micros"),
  calledOut: __t.u16().name("called_out"),
  awayThisQ: __t.bool().name("away_this_q"),
});
