// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  identity: __t.identity(),
  uid: __t.string(),
  provider: __t.u8(),
  displayName: __t.string(),
  avatarId: __t.u8(),
  xp: __t.u32(),
  level: __t.u16(),
  quizzes: __t.u16(),
  quizWins: __t.u16(),
  questions: __t.u32(),
  correct: __t.u32(),
  bestCredits: __t.i32(),
  phoneChecks: __t.u32(),
  rev: __t.u32(),
};
