// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Account = __t.object("Account", {
  identity: __t.identity(),
  uid: __t.string(),
  provider: __t.u8(),
  displayName: __t.string(),
  avatarId: __t.u8(),
  xp: __t.u32(),
  level: __t.u16(),
  quizzes: __t.u16(),
  quizWins: __t.u16(),
  questions: __t.u32(),
  correct: __t.u32(),
  bestCredits: __t.i32(),
  phoneChecks: __t.u32(),
  createdAt: __t.timestamp(),
  lastSeen: __t.timestamp(),
  rev: __t.u32(),
});
export type Account = __Infer<typeof Account>;

export const BankMeta = __t.object("BankMeta", {
  id: __t.u8(),
  version: __t.string(),
});
export type BankMeta = __Infer<typeof BankMeta>;

export const Chat = __t.object("Chat", {
  id: __t.u64(),
  lobbyId: __t.u64(),
  senderId: __t.identity(),
  senderName: __t.string(),
  kind: __t.u8(),
  text: __t.string(),
  sentAt: __t.timestamp(),
});
export type Chat = __Infer<typeof Chat>;

export const ChatGuard = __t.object("ChatGuard", {
  identity: __t.identity(),
  windowStart: __t.u64(),
  windowCount: __t.u8(),
  lastAt: __t.u64(),
  lastText: __t.string(),
  lastCallout: __t.u64(),
});
export type ChatGuard = __Infer<typeof ChatGuard>;

export const Entry = __t.object("Entry", {
  id: __t.u64(),
  lobbyId: __t.u64(),
  questionIdx: __t.u8(),
  identity: __t.identity(),
  name: __t.string(),
  stake: __t.u16(),
  answer: __t.u8(),
  correct: __t.bool(),
  delta: __t.i32(),
  answerMillis: __t.u32(),
  onPhone: __t.bool(),
});
export type Entry = __Infer<typeof Entry>;

export const LegResult = __t.object("LegResult", {
  id: __t.u64(),
  legId: __t.u64(),
  placings: __t.array(__t.identity()),
  names: __t.array(__t.string()),
  finishedAt: __t.timestamp(),
});
export type LegResult = __Infer<typeof LegResult>;

export const Lobby = __t.object("Lobby", {
  id: __t.u64(),
  code: __t.string(),
  hostId: __t.identity(),
  status: __t.u8(),
  isPublic: __t.bool(),
  theme: __t.u8(),
  questionCount: __t.u8(),
  betSecs: __t.u8(),
  answerSecs: __t.u8(),
  teamMode: __t.bool(),
  createdAt: __t.timestamp(),
  phase: __t.u8(),
  questionIdx: __t.u8(),
  phaseEndsAt: __t.timestamp(),
  phaseStartedAt: __t.timestamp(),
  timerGen: __t.u32(),
  drawn: __t.array(__t.u64()),
  topics: __t.array(__t.u64()),
  qTopic: __t.string(),
  qIcon: __t.string(),
  qDifficulty: __t.u8(),
  qPayoutPct: __t.u16(),
  qText: __t.string(),
  qOptions: __t.array(__t.string()),
  qCorrect: __t.u8(),
  fastestName: __t.string(),
  mcText: __t.string(),
  championName: __t.string(),
  championshipLeg: __t.u64(),
  lang: __t.string(),
});
export type Lobby = __Infer<typeof Lobby>;

export const MyQuestions = __t.object("MyQuestions", {});
export type MyQuestions = __Infer<typeof MyQuestions>;

export const MyQuizLog = __t.object("MyQuizLog", {});
export type MyQuizLog = __Infer<typeof MyQuizLog>;

export const PhaseTimer = __t.object("PhaseTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  lobbyId: __t.u64(),
  gen: __t.u32(),
});
export type PhaseTimer = __Infer<typeof PhaseTimer>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  avatarId: __t.u8(),
  lobbyId: __t.u64(),
  seat: __t.u8(),
  team: __t.u8(),
  online: __t.bool(),
  ready: __t.bool(),
  kicked: __t.bool(),
  credits: __t.i32(),
  stake: __t.u16(),
  answer: __t.u8(),
  answeredAt: __t.u64(),
  lastDelta: __t.i32(),
  lastCorrect: __t.bool(),
  correct: __t.u16(),
  answered: __t.u16(),
  streak: __t.u8(),
  tabs: __t.u16(),
  attention: __t.u8(),
  attentionSince: __t.u64(),
  phoneChecks: __t.u16(),
  phoneMicros: __t.u64(),
  calledOut: __t.u16(),
  awayThisQ: __t.bool(),
});
export type Player = __Infer<typeof Player>;

export const Question = __t.object("Question", {
  id: __t.u64(),
  topicId: __t.u64(),
  difficulty: __t.u8(),
  text: __t.string(),
  correct: __t.string(),
  wrong: __t.array(__t.string()),
  authorId: __t.identity(),
  authorName: __t.string(),
  builtin: __t.bool(),
  bankKey: __t.string(),
  createdAt: __t.timestamp(),
});
export type Question = __Infer<typeof Question>;

export const QuizLog = __t.object("QuizLog", {
  id: __t.u64(),
  identity: __t.identity(),
  lobbyId: __t.u64(),
  pub: __t.string(),
  placing: __t.u8(),
  seats: __t.u8(),
  credits: __t.i32(),
  correct: __t.u16(),
  questions: __t.u16(),
  xpGained: __t.u32(),
  levelAfter: __t.u16(),
  won: __t.bool(),
  playedAt: __t.timestamp(),
});
export type QuizLog = __Infer<typeof QuizLog>;

export const ReapTimer = __t.object("ReapTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  lobbyId: __t.u64(),
});
export type ReapTimer = __Infer<typeof ReapTimer>;

export const Session = __t.object("Session", {
  connectionId: __t.connectionId(),
  identity: __t.identity(),
  startedAt: __t.timestamp(),
});
export type Session = __Infer<typeof Session>;

export const Topic = __t.object("Topic", {
  id: __t.u64(),
  name: __t.string(),
  icon: __t.string(),
  builtin: __t.bool(),
  questionCount: __t.u32(),
  authorName: __t.string(),
  createdAt: __t.timestamp(),
  lang: __t.string(),
});
export type Topic = __Infer<typeof Topic>;

